import type { Metadata } from "next";
import { Dosis, Inter } from "next/font/google";
import { headers } from "next/headers";
import { TRPCReactProvider } from "~/trpc/react";
import Image from "next/image";
import "./globals.css";

const dosis = Dosis({ subsets: ["latin"], variable: "--font-dosis" });
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Gerenciamento de Hábitos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className="">
      <body
        className={`${dosis.variable} ${inter.variable} flex min-h-screen flex-col items-center bg-neutral-900 pt-10`}
      >
        <TRPCReactProvider cookies="ggsgsg">
          <Image src="/logo.svg" width={200} height={200} alt="logo projeto" />
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
